### ISSUE TITLE
GET CENkeys (in time range) endpoint missing

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/coepi-backend-aws#3] opened 2020-04-07 00:23 UTC
Mobile app needs to download a list of CENkeys which have reported symptoms. Only if a match is established the app will request specific report for a given CENkey (see https://github.com/Co-Epi/cen-server)

Are there plans to support the above described flow?

**Comment by bhushanRamnani** [comment] 2020-04-07 01:48
So as per the latest version of the protocol described here -> https://github.com/Co-Epi/CEN, we'll be moving to having CEK_0 and periods associated with reports as opposed to raw cen keys. So this API is designed to be more in-line with that model, even though it currently returns raw CEN keys.

**Comment by bhushanRamnani** [comment] 2020-04-08 23:25
By design. Closing.

**Closed by bhushanRamnani** 2020-04-08 23:25 UTC
